on:
  workflow_dispatch:
    inputs:
      os:
        description: 'The type of machine to run the job on'
        default: 'ubuntu-latest'
        required: true
        type: choice
        options:
          - 'ubuntu-latest'
          - 'macos-latest'
          - 'windows-latest'
      uri:
        description: 'URI of JDK archive file to test'
        required: true
        type: string
      test-repository:
        description: 'Check out sources of this JDK repository'
        default: 'openjdk/jdk'
        required: true
        type: string
      test-reference:
        description: 'The branch, tag or SHA to check out'
        default: 'master'
        required: true
        type: string

jobs:
  test:
    name: "Setup JDK from URI on ${{ github.event.inputs.os }}"
    runs-on: ${{ github.event.inputs.os }}
    steps:
      - name: 'Set up JDK'
        id: setup
        uses: oracle-actions/setup-java@v1
        with:
          uri: ${{ github.event.inputs.uri }}
      - name: 'Print Java version'
        run: java -version
      - name: 'Check out test repository'
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.inputs.test-repository }}
          ref:  ${{ github.event.inputs.test-reference }}
      - name: 'List entries of test/ directory'
        shell: bash
        run: ls -l test/
