on:
  workflow_dispatch:
    inputs:
      os:
        description: 'The type of machine to run the job on'
        default: 'ubuntu-latest'
        required: true
        type: choice
        options:
          - 'ubuntu-latest'
          - 'macos-latest'
          - 'windows-latest'
      uri:
        description: 'URI of JDK archive file to download'
        required: true
        type: string
      install:
        description: 'Run actions/setup-java to install the downloaded JDK'
        default: 'true'
        required: true
        type: boolean

jobs:
  test:
    name: "Setup JDK from URI on ${{ github.event.inputs.os }}"
    runs-on: ${{ github.event.inputs.os }}
    steps:
      - name: 'Set up JDK'
        id: setup
        uses: oracle-actions/setup-java@v1
        with:
          uri: ${{ github.event.inputs.uri }}
          install: ${{ github.event.inputs.install }}
      - name: 'Print Java version'
        run: java -version
